-- Add columns for extended analytics
ALTER TABLE public.channels
ADD COLUMN IF NOT EXISTS recent_posts_stats JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS language_stats JSONB DEFAULT NULL,
ADD COLUMN IF NOT EXISTS premium_percentage NUMERIC DEFAULT NULL,
ADD COLUMN IF NOT EXISTS notifications_enabled NUMERIC DEFAULT NULL,
ADD COLUMN IF NOT EXISTS growth_rate NUMERIC DEFAULT NULL,
ADD COLUMN IF NOT EXISTS top_hours JSONB DEFAULT NULL;